### ISSUE TITLE
Documentation Update - SB field for prob_calc

### ISSUE THREAD

**Issue by CollinMurdock** [cran/runexp#1]
## What

The `Details` section lists the required columns for the `playerData` argument. The `SB` column is missing from this list. 

## Why

Users get the following error if `SB` is not a column in their input, so it should be documented.

```
Error in if (SB_[ii] >= (Teams_SBA - 0.1)) { : 
  missing value where TRUE/FALSE needed
```

:)

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
