### ISSUE TITLE
Option to disable simulation printing

### ISSUE THREAD

**Issue by CollinMurdock** [cran/runexp#2]
## What 

Upon execution, the `sim` function will print to the console a message in the form: 

`Simulator is running x game reps. with x innings.`

This could be an optional feature as a parameter in the function.

## Why

When running many simulations in a loop, it will print this step every run through. This is slightly annoying because a user will lose all of their output from before the execution. More importantly, a `print` step slows down the execution. In general, I/O operations require a buffer allocation and a write to file. I don't know how much improvement you will get from making this step optional, though I bet for a large batch of simulations it won't be negligible.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!

**Comment by CollinMurdock** [comment]
Oh, sorry, I had my repos mixed up! Thanks!
